import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("geofences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeofenceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="geofences.geofence",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_events",
                        to="devices.device",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("entered", "Entered"), ("exited", "Exited")],
                        max_length=10,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["device", "-occurred_at"],
                        name="gfev_device_time_idx",
                    ),
                    models.Index(
                        fields=["geofence", "-occurred_at"],
                        name="gfev_fence_time_idx",
                    ),
                ],
            },
        ),
    ]
# Generated by Django 5.2.13 on 2026-04-14 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=50)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='geofences.geofence')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['device_id', '-occurred_at'], name='geofences_g_device__9f0c6a_idx'), models.Index(fields=['geofence', '-occurred_at'], name='geofences_g_geofenc_76570b_idx')],
            },
        ),
    ]
